name = input("Enter your name: ")
age = input("Enter your age: ")
occup = input("Enter your occupation: ")
int = input("Enter your other interests: ")
print("My name is " + name + "." + " " + "I am currently " + age + "." + " " + "I am currently a " + occup + "." + " " + "My interests are " + int + ".")